### ISSUE TITLE
Switch to Codex Beta Model for free OpenAI API requests

### ISSUE THREAD

**Issue by ezzcodeezzlife** [1998code/Swift2HTML#2]
Codex is currently in invite beta. It may even create better code results

**Comment by 1998code** [comment]
@ezzcodeezzlife Do you mean ```code-davinci-002```? 🤔
It is currently a limited beta, invitation is not required since months ago 😺
https://beta.openai.com/docs/models/codex

**Comment by ezzcodeezzlife** [comment]
@1998code oh wow. yes thats what i mean. i guess you are currently using davinci-text

**Comment by 1998code** [comment]
🙂 ```/pages/api/openai.ts```

![CleanShot 2022-12-18 at 20 18 30@2x](https://user-images.githubusercontent.com/54872601/208297995-3d9cac17-a45d-426d-914a-10c7836bb518.png)
